export * from '#/presentation/protocols'
export * from '#/presentation/test'
export * from '#/domain/models/exercises/exercise'
export * from '#/domain/usecases/exercise/check-exercise-by-id'
export * from '#/domain/usecases/exercise/update-exercise'
export * from '#/domain/test'
